const {
  TILES, TOP_IDS, RIGHT_IDS, BOTTOM_IDS, LEFT_IDS, STORAGE, PROFILE_PREFIX, THEMES, SPECIAL_START_PASS_REWARD
} = window.AW_CONFIG;
const { state, defaultPlayer, defaultSave } = window.AW_STATE;
const FULL_HEARTBEAT_TIMEOUT_MS = 30000;
const { saveState, loadState, exportState, importState } = window.AW_SAVE;
const bridge = window.AW_BRIDGE.createBridge();

const BONUS_EVENTS=[
  {name:'Coin shower', text:'+70 coins', apply:p=>{p.coins+=70;}},
  {name:'XP burst', text:'+60 XP', apply:p=>addXpToPlayer(p,60)},
  {name:'Turbo turn', text:'+1 bonus turn', apply:p=>{p.bonusTurns++;}},
  {name:'Lucky chest', text:'Chest rar', apply:p=>grantChest(p,'rare')},
  {name:'Mixed boost', text:'+30 coins + 25 XP + bonus turn', apply:p=>{p.coins+=30;addXpToPlayer(p,25);p.bonusTurns++;}},
];
const TRAP_EVENTS=[
  {name:'Taxă', text:'-50 coins', apply:p=>{p.coins=Math.max(0,p.coins-50);}},
  {name:'Skip', text:'pierzi următoarea tură', apply:p=>{p.skipTurns++;}},
  {name:'Reverse', text:'te întorci 2 tile-uri', apply:p=>{p.position=(p.position-2+TILES.length)%TILES.length;}},
  {name:'No bonus', text:'pierzi toate bonus turn-urile', apply:p=>{p.bonusTurns=0;}},
  {name:'Heavy trap', text:'-35 coins și skip 1', apply:p=>{p.coins=Math.max(0,p.coins-35);p.skipTurns++;}},
];
const SHOP_ITEMS=[
  {id:'shield', icon:'🛡️', name:'Shield', price:120, desc:'Anulează o CAPCANĂ', buy:p=>p.inventory.shield=(p.inventory.shield||0)+1},
  {id:'reroll', icon:'🎲', name:'Reroll', price:90, desc:'Re-aruncare instant', buy:p=>p.inventory.reroll=(p.inventory.reroll||0)+1},
  {id:'x2', icon:'💎', name:'x2 reward', price:150, desc:'Dubleză reward-ul următoarei victorii', buy:p=>p.inventory.double=(p.inventory.double||0)+1},
  {id:'theme', icon:'🌈', name:'Theme token', price:80, desc:'Doar colecție / flavor', buy:p=>p.inventory.themeToken=(p.inventory.themeToken||0)+1},
];
const TREE=[
  {id:'unlock_ai', name:'AI Access', desc:'Deblochează universal modul AI', need:p=>p.level>=2},
  {id:'unlock_quiz', name:'Quiz Access', desc:'Deblochează Skill+Quiz', need:p=>p.level>=3},
  {id:'unlock_full', name:'Full Access', desc:'Deblochează rapid Full Game', need:p=>p.level>=4},
  {id:'bonus_master', name:'Bonus Master', desc:'+10 coins la fiecare BONUS', need:p=>p.totalWins>=5},
  {id:'start_runner', name:'Start Runner', desc:'+15 XP extra la pass START', need:p=>p.boardPasses>=3},
  {id:'trap_resist', name:'Trap Resist', desc:'50% șansă să ignori trap dacă ai shield', need:p=>p.completed.length>=4},
];
const BADGES=[
  {id:'first_win', icon:'🏆', rarity:'Common', ok:p=>p.totalWins>=1},
  {id:'triple_bonus', icon:'⭐', rarity:'Rare', ok:p=>p.bonusHits>=3},
  {id:'trap_survivor', icon:'💀', rarity:'Rare', ok:p=>p.trapHits>=3},
  {id:'basket_master', icon:'🏀', rarity:'Epic', ok:p=>(p.stats.basketWins||0)>=4},
  {id:'full_runner', icon:'🕹️', rarity:'Epic', ok:p=>p.full.finished>=2},
  {id:'collector', icon:'🎖️', rarity:'Legendary', ok:p=>Object.keys(p.badges).filter(k=>p.badges[k]).length>=5},
];
const QUESTS=[
  {id:'q_bonus', title:'Lovește 3 BONUS', target:3, progress:p=>p.bonusHits||0, reward:{coins:100,xp:70}},
  {id:'q_start', title:'Treci de START de 4 ori', target:4, progress:p=>p.boardPasses||0, reward:{coins:120,xp:80}},
  {id:'q_full', title:'Termină 2 full games', target:2, progress:p=>p.full.finished||0, reward:{coins:140,xp:100}},
  {id:'q_fusion', title:'2 victorii Fusion', target:2, progress:p=>p.stats.fusionWins||0, reward:{coins:100,xp:90}},
  {id:'q_shop', title:'Cumpără 3 iteme', target:3, progress:p=>p.shopBuys||0, reward:{coins:80,xp:75}},
];

function q(id){return document.getElementById(id)}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function tile(i){return TILES[i]}
function currentPlayer(){return state.players[state.activePlayer]}
function currentTile(){return tile(currentPlayer().position)}
function levelNeed(l){return 100+(l-1)*65}
function safeText(s){return String(s).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}

function addXpToPlayer(p,amount){p.xp+=amount;while(p.xp>=levelNeed(p.level)){p.xp-=levelNeed(p.level);p.level++;p.bonusTurns++;toast(`${p.name} a urcat la level ${p.level} și a primit bonus turn!`,'green')}}
function grantChest(p,rarity='common'){p.chests[rarity]=(p.chests[rarity]||0)+1;const roll=Math.random();if(rarity==='rare'&&roll<.45){p.coins+=90}else if(rarity==='rare'){addXpToPlayer(p,55)}else if(rarity==='epic'){p.coins+=130;addXpToPlayer(p,80);p.bonusTurns++}else{p.coins+=40}}

function save(){saveState(state)}
function load(){return loadState(state)}
function ensurePlayers(){while(state.players.length<state.multiplayerCount)state.players.push(defaultPlayer(state.players.length));state.players=state.players.slice(0,state.multiplayerCount);if(state.activePlayer>=state.players.length)state.activePlayer=0;state.selectedTile=Math.max(0,Math.min(state.selectedTile,TILES.length-1))}

function dailyKey(){const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
function hash(s){let h=0;for(let i=0;i<s.length;i++)h=((h<<5)-h)+s.charCodeAt(i);return Math.abs(h)}
function buildDaily(){const k=dailyKey();const idx=1+(hash(k)% (TILES.length-1));const diff=['easy','medium','hard'][hash(k+'d')%3];return {key:k,tile:idx,diff,coins:80,xp:60}}

function renderTopStats(){const p=currentPlayer();q('top-stats').innerHTML=`
  <div class="stat"><div class="k">Jucător curent</div><div class="v">${p.name}</div></div>
  <div class="stat"><div class="k">Tile curent</div><div class="v">${safeText(tile(p.position).name)}</div></div>
  <div class="stat"><div class="k">Mod selectat</div><div class="v">${state.mode||'—'}</div></div>
  <div class="stat"><div class="k">Coins</div><div class="v">${p.coins}</div></div>
  <div class="stat"><div class="k">XP / Level</div><div class="v">${p.xp} / ${p.level}</div></div>
  <div class="stat"><div class="k">Victorii</div><div class="v">${p.totalWins}</div></div>`
}

function tileState(player,idx){if(player.position===idx)return {label:'CURRENT',cls:'current'};if(player.completed.includes(idx))return {label:'DONE',cls:'completed'};if(player.visited.includes(idx))return {label:'VISITED',cls:'visited'};return {label:TILES[idx].type==='special'?'SPECIAL':'OPEN',cls:''}}


function tileIconMarkup(t){
  const key=(t.id||'')+' '+(t.name||'');
  if(key.includes('start')) return `<svg viewBox="0 0 64 64" aria-hidden="true"><path class="stroke white" d="M14 12v40"/><path class="stroke white" d="M18 14h26l-6 8 6 8H18z"/><path class="stroke" fill="url(#chk)" d="M18 14h26l-6 8 6 8H18z"/><defs><pattern id="chk" width="8" height="8" patternUnits="userSpaceOnUse"><rect width="8" height="8" fill="#fff"/><rect width="4" height="4" fill="#101827"/><rect x="4" y="4" width="4" height="4" fill="#101827"/></pattern></defs></svg>`;
  if(key.includes('basket')) return `<svg viewBox="0 0 64 64"><circle cx="32" cy="32" r="19" class="stroke orange"/><path d="M13 32h38M32 13c8 7 8 31 0 38M32 13c-8 7-8 31 0 38" class="stroke" fill="none" stroke="#9b3a00" stroke-width="2.6"/></svg>`;
  if(key.includes('labirint')||key.includes('maze')) return `<svg viewBox="0 0 64 64"><path class="stroke white" d="M10 14h44v36H10z"/><path class="stroke green" stroke="#57d66f" fill="none" d="M16 20h12v10h8V20h12v18H36v8h-8V34H16z"/><path class="stroke blue" d="M20 18v-4M44 50v-4" stroke="#2f94ff"/></svg>`;
  if(key.includes('bonus')) return `<svg viewBox="0 0 64 64"><path class="stroke gold" d="M32 8l6.8 14.4L54 24l-11 10.5L46 50 32 41.8 18 50l3-15.5L10 24l15.2-1.6z"/></svg>`;
  if(key.includes('bomb')||key.includes('bomba')||key.includes('bomber')) return `<svg viewBox="0 0 64 64"><circle cx="28" cy="36" r="18" class="stroke gray" fill="#2f3744"/><circle cx="22" cy="30" r="3" fill="#9aa7b4"/><path class="stroke" d="M37 19l6-6 6 6" fill="none" stroke="#d7b083"/><path class="stroke" d="M43 19c2 0 6 1 8 4" fill="none" stroke="#d7b083"/><path class="stroke" d="M50 10c2 2 2 5 0 7" fill="none" stroke="#ff4b2b"/><circle cx="54" cy="10" r="5" class="stroke red"/></svg>`;
  if(key.includes('void')||key.includes('shooter')) return `<svg viewBox="0 0 64 64"><path class="stroke white" d="M12 42l20-20 20 10-10 20z" fill="#e7eef9"/><path class="stroke cyan" d="M12 42l10 10 10-10-10-10z"/><path class="stroke red" d="M42 24l8-8 6 14-12 2z"/><path class="stroke orange" d="M18 48l-6 10 10-6"/></svg>`;
  if(key.includes('fusion')||key.includes('tufusion')) return `<svg viewBox="0 0 64 64"><path class="stroke cyan" d="M16 16c8-6 18-4 22 5 2 5 1 10-2 15-2 3-1 7 2 10-10 4-22 0-26-10-4-8-1-16 4-20z"/><path class="stroke gold" d="M48 16c-8-6-18-4-22 5-2 5-1 10 2 15 2 3 1 7-2 10 10 4 22 0 26-10 4-8 1-16-4-20z"/><path class="stroke red" d="M48 12l5 5m0-5l-5 5"/></svg>`;
  if(key.includes('capc')||key.includes('skull')) return `<svg viewBox="0 0 64 64"><path class="stroke white" d="M32 12c11 0 20 8 20 19 0 8-5 12-10 14v7H22v-7c-5-2-10-6-10-14 0-11 9-19 20-19z"/><circle cx="25" cy="29" r="4" class="dark"/><circle cx="39" cy="29" r="4" class="dark"/><path class="stroke dark" d="M28 40h8"/></svg>`;
  if(key.includes('hockey')) return `<svg viewBox="0 0 64 64"><path class="stroke orange" d="M40 14l8 4-12 26H24"/><rect x="16" y="40" width="16" height="6" rx="2" class="stroke white" fill="#f7f8fb"/><circle cx="42" cy="46" r="5" class="stroke dark"/></svg>`;
  if(key.includes('tictacto')||key.includes('ttt')) return `<svg viewBox="0 0 64 64"><path class="stroke red" d="M16 16l32 32M48 16L16 48"/><circle cx="32" cy="32" r="0.1" fill="none"/></svg>`;
  if(key.includes('bounce')) return `<svg viewBox="0 0 64 64"><circle cx="32" cy="32" r="20" class="stroke blue" fill="#1692ff"/></svg>`;
  if(key.includes('pvai')) return `<svg viewBox="0 0 64 64"><path class="stroke white" d="M18 18l12 12-12 12M46 18L34 30l12 12"/><path class="stroke gold" d="M22 46l8-8M42 46l-8-8"/></svg>`;
  if(key.includes('mem')) return `<svg viewBox="0 0 64 64"><rect x="18" y="10" width="28" height="42" rx="4" class="stroke white"/><path class="stroke purple" d="M32 20v22M21 31h22"/><path class="stroke gold" d="M24 22l3 4 5-1M40 22l-3 4-5-1"/></svg>`;
  if(key.includes('breakout')) return `<svg viewBox="0 0 64 64"><path class="stroke beige" d="M14 18h28l8 8v22H22l-8-8z"/><path class="stroke" d="M42 18v8h8M18 42h6M18 36h10" fill="none" stroke="#7a5a38"/><path class="stroke red" d="M18 34V24l6 6"/></svg>`;
  return `<svg viewBox="0 0 64 64"><circle cx="32" cy="32" r="18" class="stroke cyan"/></svg>`;
}

function renderBoard(){
  const p=currentPlayer();
  const cell=(idx)=>{const t=tile(idx);const s=tileState(p,idx);const corner=[0,6,12,18].includes(idx);return `<div class="tile-wrap" data-idx="${idx}" onclick="selectTile(${idx})"><button class="tile ${t.type==='special'?'special':''} ${s.cls} ${corner?'corner':''}"><div class="idx">${idx}</div><div class="icon">${tileIconMarkup(t)}</div><div class="name">${safeText(t.name)}</div><div class="state">${s.label}</div><div class="dot"></div></button></div>`};
  q('topRow').innerHTML=TOP_IDS.map(cell).join('');
  q('rightCol').innerHTML=RIGHT_IDS.map(cell).join('');
  q('bottomRow').innerHTML=BOTTOM_IDS.slice().reverse().map(cell).join('');
  q('leftCol').innerHTML=LEFT_IDS.slice().reverse().map(cell).join('');
  requestAnimationFrame(()=>{drawConnectors();moveTokenTo(p.position,false)})
}

function selectTile(idx){state.selectedTile=idx;renderScreen('details')}

function centerOfIdx(idx){const wrap=q('boardWrap');const el=document.querySelector(`.tile-wrap[data-idx="${idx}"]`);if(!wrap||!el)return null;const a=wrap.getBoundingClientRect(),b=el.getBoundingClientRect();return {x:b.left-a.left+b.width/2,y:b.top-a.top+b.height/2}}
function drawConnectors(){const host=q('connectors');host.innerHTML='';for(let i=0;i<TILES.length;i++){const a=centerOfIdx(i),b=centerOfIdx((i+1)%TILES.length);if(!a||!b)continue;const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;const d=document.createElement('div');d.className='connector';d.style.left=a.x+'px';d.style.top=(a.y-4)+'px';d.style.width=len+'px';d.style.transform=`rotate(${ang}deg)`;host.appendChild(d)}}
function moveTokenTo(idx,animate=true){const pt=centerOfIdx(idx);if(!pt)return;const token=q('boardToken');token.style.left=pt.x+'px';token.style.top=pt.y+'px'}
function showTrail(a,b){const ta=centerOfIdx(a),tb=centerOfIdx(b),trail=q('boardTrail');if(!ta||!tb)return;const dx=tb.x-ta.x,dy=tb.y-ta.y,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;trail.style.left=ta.x+'px';trail.style.top=(ta.y-5)+'px';trail.style.width=len+'px';trail.style.transform=`rotate(${ang}deg)`;trail.style.opacity=1;setTimeout(()=>trail.style.opacity=0,220)}

function renderPlayers(){q('playersCard').innerHTML=`<div class="section-k">Multiplayer local</div><div class="btnrow" style="margin:10px 0"><button class="btn-alt" onclick="setPlayerCount(2)">2P</button><button class="btn-alt" onclick="setPlayerCount(3)">3P</button><button class="btn-alt" onclick="setPlayerCount(4)">4P</button></div><div class="players">${state.players.map((p,i)=>`<div class="player-card ${i===state.activePlayer?'active':''}"><div style="display:flex;justify-content:space-between;gap:8px"><b>${p.name}</b><span class="tag">${i===state.activePlayer?'ACTIVE':'WAIT'}</span></div><div class="tiny">Tile ${p.position} · Coins ${p.coins} · Lv ${p.level} · Wins ${p.totalWins}</div><div class="tiny">Bonus turns ${p.bonusTurns} · Skip ${p.skipTurns}</div></div>`).join('')}</div>`;q('turnPlayer').textContent=currentPlayer().name}
function setPlayerCount(n){state.multiplayerCount=Math.max(2,Math.min(4,Number(n)||2));state.mode=null;state.difficulty=null;ensurePlayers();save();renderAll();renderScreen('details');toast(`Multiplayer setat la ${state.multiplayerCount} jucători`,'green')}

function renderDaily(){const d=state.daily,t=tile(d.tile);q('dailyCard').innerHTML=`<div class="section-k">Daily</div><div style="font-weight:1000;font-size:18px;margin:8px 0">${t.icon} ${t.name} · AI ${d.diff}</div><div class="tiny">Bonus daily: +${d.coins} coins și +${d.xp} XP pe victoria mini în AI ${d.diff}.</div>`}

function renderQuests(){const p=currentPlayer();const items=QUESTS.map(qs=>{const pr=Math.min(qs.target,qs.progress(p));const done=p.questsDone.includes(qs.id);return `<div class="quest"><div style="font-weight:1000">${done?'✅':'🎯'} ${qs.title}</div><div class="tiny">${pr}/${qs.target} · reward ${qs.reward.coins} coins + ${qs.reward.xp} XP</div><div class="bar"><span style="width:${Math.round(pr/qs.target*100)}%"></span></div></div>`}).join('');q('questsCard').innerHTML=`<div class="section-k">Quest-uri</div><div class="list" style="margin-top:10px">${items}</div>`}
function resolveQuests(p){for(const qs of QUESTS){const pr=qs.progress(p);if(pr>=qs.target&&!p.questsDone.includes(qs.id)){p.questsDone.push(qs.id);p.coins+=qs.reward.coins;addXpToPlayer(p,qs.reward.xp);toast(`${p.name} a completat quest: ${qs.title}`,'green')}}}

function renderInventory(){const p=currentPlayer();q('inventoryCard').innerHTML=`<div class="section-k">Inventory</div><div class="inventory" style="margin-top:10px"><div class="event-card"><b>🛡️ Shield</b><div class="tiny">${p.inventory.shield||0}</div></div><div class="event-card"><b>🎲 Reroll</b><div class="tiny">${p.inventory.reroll||0}</div></div><div class="event-card"><b>💎 x2 Reward</b><div class="tiny">${p.inventory.double||0}</div></div><div class="event-card"><b>📦 Chests</b><div class="tiny">C ${p.chests.common||0} · R ${p.chests.rare||0} · E ${p.chests.epic||0}</div></div></div>`}

function renderShop(){q('shopCard').innerHTML=`<div class="section-k">Shop</div><div class="shopgrid" style="margin-top:10px">${SHOP_ITEMS.map(it=>`<div class="shop-item"><div style="font-weight:1000">${it.icon} ${it.name}</div><div class="tiny">${it.desc}</div><div class="tiny" style="margin:6px 0 10px">${it.price} coins</div><button class="btn-main" onclick="buyItem('${it.id}')">Cumpără</button></div>`).join('')}</div>`}
function buyItem(id){const p=currentPlayer();const it=SHOP_ITEMS.find(x=>x.id===id);if(!it)return;if(p.coins<it.price)return toast('Coins insuficiente','red');p.coins-=it.price;it.buy(p);p.shopBuys++;save();renderAll();toast(`${p.name} a cumpărat ${it.name}`,'green')}

function renderTree(){const p=currentPlayer();for(const n of TREE)p.unlocks[n.id]=n.need(p);q('treeCard').innerHTML=`<div class="section-k">Unlock tree</div><div class="treegrid" style="margin-top:10px">${TREE.map(n=>`<div class="tree-item"><div style="font-weight:1000">${p.unlocks[n.id]?'✅':'🔒'} ${n.name}</div><div class="tiny">${n.desc}</div></div>`).join('')}</div>`}

function renderBadges(){const p=currentPlayer();for(const b of BADGES)p.badges[b.id]=b.ok(p);q('badgeCard').innerHTML=`<div class="section-k">Badges / rarități</div><div class="badgegrid" style="margin-top:10px">${BADGES.map(b=>`<div class="badge ${p.badges[b.id]?'':'locked'}"><div class="icon">${b.icon}</div><div style="font-weight:1000">${b.id}</div><div class="tiny">${b.rarity}</div></div>`).join('')}</div>`}

function renderAll(){renderTopStats();renderBoard();renderPlayers();renderDaily();renderQuests();renderInventory();renderShop();renderTree();renderBadges();q('soundBtn').textContent=state.sound?'🔊 Sound':'🔇 Sound';q('bonusBtn').textContent=`✨ Bonus turn (${currentPlayer().bonusTurns})`;q('lastRoll').textContent=currentPlayer().lastRoll||'—'}

function rewardBaseForTile(t){if(t.type==='special')return 60;return t.reward||100}
function currentReward(mult=1){return Math.round(rewardBaseForTile(currentTile())*mult)}
function claimReward(win,extra={coins:0,xp:0,score:0,partial:1,result:'finish',source:'mini'}){const p=currentPlayer();let coins=Math.max(1,Math.round(currentReward(win?1:0.5)*(extra.partial??1))+extra.coins);let xp=Math.max(5,Math.round(currentReward()*.55*(extra.partial??1))+extra.xp);if(p.inventory.double>0&&win){coins*=2;xp*=2;p.inventory.double--;toast('x2 reward activat','purple')}p.coins+=coins;addXpToPlayer(p,xp);if(win)p.totalWins++;const fam=currentTile().family;if(fam)p.stats[fam+'Wins']=(p.stats[fam+'Wins']||0)+(win?1:0);if(win&&!p.completed.includes(p.position))p.completed.push(p.position);p.history.unshift({ts:Date.now(),tile:p.position,result:extra.result,coins,xp,score:extra.score,source:extra.source});p.history=p.history.slice(0,120);resolveQuests(p);save();renderAll();return {coins,xp}}

function setHint(t){q('turnHint').textContent=t}
function toggleSound(){state.sound=!state.sound;save();renderAll()}
function toast(text,type=''){const el=q('toast');el.className='toast show';el.innerHTML=`<div class="chiprow"><div class="chip ${type}">${safeText(text)}</div></div>`;setTimeout(()=>el.className='toast',1800)}
function burst(){for(let i=0;i<26;i++){const d=document.createElement('div');d.className='particle';d.style.left=(innerWidth/2)+'px';d.style.top=(innerHeight/2)+'px';d.style.setProperty('--dx',rand(-220,220)+'px');d.style.setProperty('--dy',rand(-220,220)+'px');document.body.appendChild(d);setTimeout(()=>d.remove(),920)}}
function nextTheme(){state.themeIndex=(state.themeIndex+1)%THEMES.length;document.body.className=THEMES[state.themeIndex];save()}

async function rollDice(){if(state.animating)return;const p=currentPlayer();if(p.skipTurns>0){p.skipTurns--;toast(`${p.name} sare tura`,'red');endTurn();return}const dice=q('dice');dice.classList.add('rolling');q('rollBtn').disabled=true;for(let i=0;i<10;i++){dice.textContent=rand(1,6);await sleep(70)}const n=rand(1,6);dice.classList.remove('rolling');dice.textContent=n;p.lastRoll=n;q('lastRoll').textContent=n;await moveBy(n);q('rollBtn').disabled=false}

async function useBonusTurn(){const p=currentPlayer();if(p.bonusTurns<=0)return;p.bonusTurns--;save();renderAll();await rollDice()}

async function moveBy(steps){state.animating=true;const p=currentPlayer();for(let i=0;i<steps;i++){const prev=p.position;p.position=(p.position+1)%TILES.length;if(p.position===0){p.boardPasses++;p.coins+=SPECIAL_START_PASS_REWARD.coins;addXpToPlayer(p,SPECIAL_START_PASS_REWARD.xp+(p.unlocks.start_runner?15:0));toast(`${p.name} a trecut de START`,'gold')}if(!p.visited.includes(p.position))p.visited.push(p.position);showTrail(prev,p.position);moveTokenTo(p.position,true);await sleep(270)}state.selectedTile=p.position;state.animating=false;save();renderAll();resolveLanding()}

function resolveLanding(){const p=currentPlayer(),t=currentTile();if(t.type==='special'){if(t.effect==='start'){p.coins+=50;addXpToPlayer(p,30);toast('Landing pe START: +50 coins +30 XP','gold');renderScreen('event',`<div class="event-card"><b>🏁 START</b><div class="tiny">Landing reward acordat.</div></div>`,true);return endTurnPrompt()}if(t.effect==='bonus')return resolveBonus();if(t.effect==='trap')return resolveTrap()}state.mode=null;state.difficulty=null;renderScreen('modes')}
function resolveBonus(){const p=currentPlayer();p.bonusHits++;const ev=BONUS_EVENTS[rand(0,BONUS_EVENTS.length-1)];if(p.unlocks.bonus_master)p.coins+=10;ev.apply(p);save();renderAll();renderScreen('event',`<div class="event-card"><h3>⭐ BONUS</h3><p class="muted">${ev.name}: ${ev.text}</p></div>`,true);toast(`${p.name}: ${ev.name}`,'green');endTurnPrompt(false,true)}
function resolveTrap(){const p=currentPlayer();if((p.inventory.shield||0)>0){p.inventory.shield--;toast('Shield a blocat CAPCANA','green');renderScreen('event',`<div class="event-card"><h3>🛡️ CAPCANĂ blocată</h3><p class="muted">Shield consumat. Nu primești penalizare.</p></div>`,true);save();renderAll();return endTurnPrompt()}p.trapHits++;const ev=TRAP_EVENTS[rand(0,TRAP_EVENTS.length-1)];ev.apply(p);save();renderAll();renderScreen('event',`<div class="event-card"><h3>💀 CAPCANĂ</h3><p class="muted">${ev.name}: ${ev.text}</p></div>`,true);toast(`${p.name}: ${ev.name}`,'red');endTurnPrompt()}

function modeUnlocked(mode,p=currentPlayer()){if(mode==='solo')return true;if(mode==='ai')return p.level>=2||p.unlocks.unlock_ai;if(mode==='quiz')return p.level>=3||p.unlocks.unlock_quiz;if(mode==='full')return p.level>=2||p.unlocks.unlock_full;return false}
function renderTabs(active='modes'){return `<div class="screen-tabs"><button class="${active==='modes'?'btn-main':'btn-alt'}" onclick="renderScreen('modes')">🎮 Moduri</button><button class="${active==='details'?'btn-main':'btn-alt'}" onclick="renderScreen('details')">ℹ️ Detalii</button><button class="${active==='stats'?'btn-main':'btn-alt'}" onclick="renderScreen('stats')">📊 Stats</button></div>`}
function renderScreen(tab,custom='',autoEnd=false){const p=currentPlayer(),t=currentTile();state.screenTab=tab;
  if(tab==='event'){q('screen').innerHTML=`${renderTabs('details')}${custom}<div class="btnrow" style="margin-top:12px"><button class="btn-alt" onclick="endTurn()">Tura următoare</button></div>`;if(autoEnd)return;}
  if(tab==='details'){q('screen').innerHTML=`${renderTabs('details')}<h3>${t.icon} ${t.name}</h3><p class="muted">${t.type==='special'?'Tile special cu efect imediat.':'Family: '+t.family+' · kind: '+t.kind+' · reward bază: '+t.reward}</p><div class="hud"><div class="box"><div class="k">Poziție</div><div class="v">${p.position}</div></div><div class="box"><div class="k">Visited</div><div class="v">${p.visited.length}</div></div><div class="box"><div class="k">Completed</div><div class="v">${p.completed.length}</div></div><div class="box"><div class="k">Reward</div><div class="v">${rewardBaseForTile(t)}</div></div></div>`;return}
  if(tab==='stats'){q('screen').innerHTML=`${renderTabs('stats')}<h3>Stats · ${p.name}</h3><div class="hud"><div class="box"><div class="k">Level</div><div class="v">${p.level}</div></div><div class="box"><div class="k">XP need</div><div class="v">${levelNeed(p.level)}</div></div><div class="box"><div class="k">Full runs</div><div class="v">${p.full.finished}</div></div><div class="box"><div class="k">Best family</div><div class="v">${Object.entries(p.stats).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—'}</div></div></div><div class="xpbar"><div class="xpfill" style="width:${Math.round(p.xp/levelNeed(p.level)*100)}%"></div></div><div class="log" style="margin-top:12px">Coins ${p.coins} · Wins ${p.totalWins} · Pass START ${p.boardPasses} · BONUS ${p.bonusHits} · CAPCANĂ ${p.trapHits}</div>`;return}
  if(t.type==='special'){q('screen').innerHTML=`${renderTabs('modes')}<h3>${t.icon} ${t.name}</h3><p class="muted">Acest tile rezolvă efectul automat. Apasă pentru tura următoare.</p><button class="btn-alt" onclick="endTurn()">Tura următoare</button>`;return}
  q('screen').innerHTML=`${renderTabs('modes')}<h3>${t.icon} ${t.name}</h3><p class="muted">Alege modul. Full Game folosește linkul original în overlay. Pentru site-uri externe, reward-ul automat depinde de <code>postMessage</code>; altfel rămâne fallback manual.</p><div class="choices">${['solo','ai','quiz','full'].map(m=>`<div class="choice"><div class="i">${m==='full'?'🕹️':m==='quiz'?'🧠':m==='ai'?'🤖':'🎮'}</div><div class="t">${m.toUpperCase()}</div><div class="d">${modeUnlocked(m,p)?'Open':'Locked'}</div><button class="${m==='full'?'btn-purple':'btn-main'}" ${modeUnlocked(m,p)?`onclick="chooseMode('${m}')"`:'disabled'}>${m==='full'?'Deschide':'Alege'}</button></div>`).join('')}</div>`}

function endTurnPrompt(){setHint('Efect rezolvat. Tura următoare.');}
function endTurn(){state.mode=null;state.difficulty=null;state.activePlayer=(state.activePlayer+1)%state.players.length;save();renderAll();renderScreen('details');setHint('Jucătorul următor poate arunca zarul.')}

function chooseMode(mode){state.mode=mode;if(mode==='full')return openFullGame();if(mode==='ai'){q('screen').innerHTML=`<h3>Alege dificultatea</h3><div class="btnrow"><button class="btn-main" onclick="chooseDifficulty('easy')">Easy</button><button class="btn-main" onclick="chooseDifficulty('medium')">Medium</button><button class="btn-gold" onclick="chooseDifficulty('hard')">Hard</button></div>`;return}state.difficulty=null;launchMini()}
function chooseDifficulty(d){state.difficulty=d;launchMini()}

function launchMini(){const fam=currentTile().family;if(fam==='basket')return startBasket();if(fam==='maze')return startMaze();if(fam==='bomber')return startBomber();if(fam==='shooter')return startShooter();if(fam==='fusion')return startFusion();if(fam==='hockey')return startHockey();if(fam==='ttt')return startTTT();if(fam==='bounce')return startBounce();if(fam==='breakout')return startBreakout();if(fam==='memory')return startMemory();if(fam==='pvai')return startPvAI();}

function layoutGame(title,subtitle,hud,body,foot=''){q('screen').innerHTML=`<h3>${title}</h3><p class="muted">${subtitle}</p><div class="hud">${hud.map(h=>`<div class="box"><div class="k">${h.k}</div><div class="v" id="${h.id||''}">${h.v}</div></div>`).join('')}</div>${body}${foot?`<div class="btnrow" style="margin-top:12px">${foot}</div>`:''}`}
function finishMini(win,msg,opts={}){const r=claimReward(win,{coins:opts.extraCoins||0,xp:opts.extraXp||0,score:opts.score||0,partial:opts.partial??(win?1:.35),result:win?'win':'lose',source:'mini'});if(win)burst();q('screen').innerHTML=`<div class="log"><b>${win?'✅':'❌'} ${msg}</b><br><br>Coins +${r.coins} · XP +${r.xp}</div><div class="btnrow" style="margin-top:12px"><button class="btn-main" onclick="renderScreen('modes')">Replay</button><button class="btn-alt" onclick="endTurn()">Tura următoare</button></div>`}

function askQuiz(onWin,onLose){const pools={basket:[['Câte puncte are liberă?',['1','2','3'],0],['Ce e dunk?',['șut','slam','dribling'],1]],maze:[['Ce vrei în maze?',['ieșirea','bonus audio','skin'],0]],memory:[['Ce cauți în memory?',['perechi','chei','boss'],0]],fusion:[['Fusion combină?',['mecanici arcade','doar puzzle','doar quiz'],0]],hockey:[['Scop air hockey?',['marchezi','rotești tabla','spargi bricks'],0]],ttt:[['Ținta?',['3 în linie','4 în pătrat','2 în coloană'],0]]};const fam=currentTile().family;const qz=(pools[fam]||[['Skill check?',['da','nu','poate'],0]])[0];q('screen').innerHTML=`<h3>Bonus Quiz</h3><div class="log">${qz[0]}</div><div class="btnrow" style="margin-top:12px">${qz[1].map((a,i)=>`<button class="btn-main" onclick="quizPick(${i},${qz[2]})">${a}</button>`).join('')}</div>`;window.quizPick=(i,c)=>i===c?onWin():onLose()}

function startBasket(){
  const p=currentPlayer();
  const shotsTaken=(p.stats.basketShots||0);
  const wins=(p.stats.basketWins||0), plays=Math.max(1,(p.stats.basketPlays||0));
  const winRate=wins/plays;
  const tutorialSlow=shotsTaken<2;
  const diff=state.difficulty||'medium';
  let speed=tutorialSlow?7:(diff==='easy'?11:diff==='hard'?18:14);
  if(!tutorialSlow){speed += Math.round(shotsTaken*0.8) + (winRate>.65?2:0)}
  const zone=tutorialSlow?28:(diff==='easy'?24:diff==='hard'?11:17);
  const zoneStart=tutorialSlow?36:(diff==='easy'?34:diff==='hard'?45:40);
  let pos=0,dir=1; p.stats.basketPlays=(p.stats.basketPlays||0)+1;
  layoutGame(`${currentTile().icon} Basket Auto-Adjust`,`Primele 2 shot-uri sunt slow tutorial. Apoi viteza crește treptat după numărul de shot-uri și win-rate.`,[{k:'Shots total',v:shotsTaken,id:'bk_shots'},{k:'Zone',v:zone+'%'},{k:'Speed',v:speed},{k:'Mode',v:state.mode}],`<div class="log">Oprește markerul în zona verde.</div><div class="meter"><div class="zone" id="bk_zone"></div><div class="marker" id="bk_marker"></div></div>`,`<button class="btn-main" onclick="stopBasket()">STOP</button>`);
  q('bk_zone').style.left=zoneStart+'%';q('bk_zone').style.width=zone+'%';
  state.timer=setInterval(()=>{pos+=dir*speed*.42;if(pos>=100){pos=100;dir=-1}if(pos<=0){pos=0;dir=1}q('bk_marker').style.left=`calc(${pos}% - 7px)`},28);
  window.stopBasket=()=>{clearInterval(state.timer);p.stats.basketShots=(p.stats.basketShots||0)+1;const ok=pos>=zoneStart&&pos<=zoneStart+zone;const precision=Math.max(0,100-Math.abs(pos-(zoneStart+zone/2))*4|0);if(state.mode==='ai'){const ai=diff==='easy'?62+rand(0,8):diff==='hard'?88+rand(0,6):76+rand(0,8);if(ok&&precision>ai){p.stats.basketWins=(p.stats.basketWins||0)+1;return finishMini(true,`Tu ${precision}% vs AI ${ai}%`,{score:precision})}if(ok&&precision===ai)return finishMini(false,`Egal ${precision}%`,{score:precision,partial:.75});return finishMini(false,ok?`AI mai precis (${ai}% vs ${precision}%)`:`Ai ratat, AI ${ai}%`,{score:precision,partial:.3})}
    if(state.mode==='quiz'){if(!ok)return finishMini(false,'Ai ratat aruncarea',{score:precision,partial:.2});p.stats.basketWins=(p.stats.basketWins||0)+1;return askQuiz(()=>finishMini(true,'Shot + quiz complete',{score:precision}),()=>finishMini(false,'Quiz greșit',{score:precision,partial:.4}))}
    if(ok)p.stats.basketWins=(p.stats.basketWins||0)+1;finishMini(ok,ok?`Perfect release ${precision}%`:'Ai ratat',{score:precision,partial:ok?1:.2})}
}

function startHockey(){meterStyleGame('Hockey','Timing și reflex','hockey',state.difficulty||'medium')}
function startBounce(){meterStyleGame('Bounce','Rhythm și control','bounce',state.difficulty||'medium')}
function meterStyleGame(title,subtitle,fam,diff){const cfg={easy:{speed:10,zone:26,start:32,ai:64},medium:{speed:14,zone:18,start:40,ai:78},hard:{speed:18,zone:10,start:46,ai:90}}[diff||'medium'];let pos=0,dir=1;layoutGame(`${currentTile().icon} ${title}`,subtitle,[{k:'Zone',v:cfg.zone+'%'},{k:'Speed',v:cfg.speed},{k:'Mode',v:state.mode},{k:'AI',v:state.mode==='ai'?cfg.ai:'—'}],`<div class="meter"><div class="zone" id="m_zone"></div><div class="marker" id="m_marker"></div></div>`,`<button class="btn-main" onclick="stopMeterGame()">STOP</button>`);q('m_zone').style.left=cfg.start+'%';q('m_zone').style.width=cfg.zone+'%';state.timer=setInterval(()=>{pos+=dir*cfg.speed*.42;if(pos>=100){pos=100;dir=-1}if(pos<=0){pos=0;dir=1}q('m_marker').style.left=`calc(${pos}% - 7px)`},28);window.stopMeterGame=()=>{clearInterval(state.timer);const ok=pos>=cfg.start&&pos<=cfg.start+cfg.zone;const score=Math.max(0,100-Math.abs(pos-(cfg.start+cfg.zone/2))*4|0);if(state.mode==='ai'){if(ok&&score>cfg.ai)return finishMini(true,`Ai depășit AI (${score}% vs ${cfg.ai}%)`,{score});if(ok&&score===cfg.ai)return finishMini(false,`Egal la precizie`,{score,partial:.75});return finishMini(false,`AI mai bun sau ai ratat`,{score,partial:.25})}if(state.mode==='quiz'){if(!ok)return finishMini(false,'Skill ratat',{score,partial:.2});return askQuiz(()=>finishMini(true,'Skill + quiz OK',{score}),()=>finishMini(false,'Quiz greșit',{score,partial:.4}))}finishMini(ok,ok?'Execuție reușită':'Execuție ratată',{score,partial:ok?1:.2})}}

function startBomber(){const safe=rand(0,2);layoutGame(`${currentTile().icon} Bomber`,`Alege lada sigură.`,[{k:'Mode',v:state.mode},{k:'Reward',v:currentReward()},{k:'AI',v:state.mode==='ai'?(state.difficulty||'medium'):'—'},{k:'Risk',v:'High'}],`<div class="choices">${['Stânga','Centru','Dreapta'].map((x,i)=>`<div class="choice"><div class="i">📦</div><div class="t">${x}</div><button class="btn-main" onclick="pickBomb(${i})">Alege</button></div>`).join('')}</div>`);window.pickBomb=(i)=>{const ok=i===safe;if(state.mode==='ai'){const aiOk=Math.random()<(state.difficulty==='hard'?0.8:state.difficulty==='easy'?0.35:0.58);if(ok&&!aiOk)return finishMini(true,'Tu ai găsit safe crate',{score:100});if(ok&&aiOk)return finishMini(false,'Egal, amândoi corect',{score:80,partial:.75});return finishMini(false,aiOk?'AI a ales mai bine':'Boom',{score:25,partial:.25})}if(state.mode==='quiz'){if(!ok)return finishMini(false,'Boom',{score:20,partial:.2});return askQuiz(()=>finishMini(true,'Safe crate + quiz',{score:100}),()=>finishMini(false,'Quiz greșit',{score:45,partial:.4}))}finishMini(ok,ok?'Safe crate!':'Boom!',{score:ok?100:15,partial:ok?1:.2})}}

function startTTT(){let b=Array(9).fill('');const wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];const won=s=>wins.some(line=>line.every(i=>b[i]===s));const aiMove=()=>{const open=b.map((v,i)=>v?null:i).filter(v=>v!==null);if(!open.length)return null;if(state.mode!=='ai')return open[rand(0,open.length-1)];if(state.difficulty==='hard'&&open.includes(4))return 4;return open[rand(0,open.length-1)]};layoutGame(`${currentTile().icon} TicTacToe`,`3 în linie.`,[{k:'You',v:'X'},{k:'AI',v:'O'},{k:'Mode',v:state.mode},{k:'Reward',v:currentReward()}],`<div id="ttt" style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px">${Array.from({length:9},(_,i)=>`<button class="btn-alt" style="height:86px;font-size:28px" onclick="tttPick(${i})" id="tt${i}"></button>`).join('')}</div>`);window.tttPick=(i)=>{if(b[i])return;b[i]='X';q('tt'+i).textContent='X';if(won('X'))return state.mode==='quiz'?askQuiz(()=>finishMini(true,'TTT + quiz',{score:100}),()=>finishMini(false,'Quiz greșit',{score:45,partial:.4})):finishMini(true,'Ai câștigat TTT',{score:100});if(b.every(Boolean))return finishMini(false,'Remiză',{score:60,partial:.6});const ai=aiMove();if(ai!=null){b[ai]='O';q('tt'+ai).textContent='O';if(won('O'))return finishMini(false,'AI a câștigat',{score:35,partial:.25});if(b.every(Boolean))return finishMini(false,'Remiză',{score:60,partial:.6})}}}

function startMemory(){let cards=['✦','✦','◆','◆','●','●','⬟','⬟'];for(let i=cards.length-1;i>0;i--){const j=rand(0,i);[cards[i],cards[j]]=[cards[j],cards[i]]}let open=[],done=Array(8).fill(false),moves=0,pairs=0;layoutGame(`${currentTile().icon} Memory`,`Găsește toate perechile.`,[{k:'Moves',v:0,id:'mm1'},{k:'Pairs',v:'0/4',id:'mm2'},{k:'Mode',v:state.mode},{k:'Reward',v:currentReward()}],`<div id="mg" style="display:grid;grid-template-columns:repeat(4,1fr);gap:8px">${cards.map((_,i)=>`<button class="btn-alt" style="height:76px;font-size:24px" onclick="memFlip(${i})" id="m${i}">?</button>`).join('')}</div>`);window.memFlip=(i)=>{if(done[i]||open.includes(i)||open.length===2)return;q('m'+i).textContent=cards[i];open.push(i);if(open.length<2)return;moves++;q('mm1').textContent=moves;const[a,b]=open;if(cards[a]===cards[b]){done[a]=done[b]=true;open=[];pairs++;q('mm2').textContent=`${pairs}/4`;if(pairs===4){const score=Math.max(35,120-moves*10);if(state.mode==='quiz')return askQuiz(()=>finishMini(true,'Memory + quiz',{score}),()=>finishMini(false,'Quiz greșit',{score,partial:.4}));if(state.mode==='ai'){const ai=state.difficulty==='hard'?5:state.difficulty==='easy'?10:7;return finishMini(moves<ai,moves<ai?`Mai bun decât AI (${moves} mutări)`:`AI ar fi făcut ${ai}`,{score,partial:moves<ai?1:.35})}return finishMini(true,'Toate perechile găsite',{score})}return}setTimeout(()=>{q('m'+a).textContent='?';q('m'+b).textContent='?';open=[]},500)}}

function startBreakout(){let bricks=0,target=state.difficulty==='hard'?10:state.difficulty==='easy'?5:7,time=20,ai=0;layoutGame(`${currentTile().icon} Breakout`,`Sparge suficiente bricks înainte să expire timpul.`,[{k:'Bricks',v:0,id:'br1'},{k:'Target',v:target},{k:'Time',v:time,id:'br2'},{k:'AI',v:state.mode==='ai'?0:'—',id:'br3'}],`<div class="log">În versiunea locală simulezi bricks sparte.</div>`,`<button class="btn-main" onclick="breakBrick()">🧱 Break</button><button class="btn-alt" onclick="endBreakout()">Finish</button>`);if(state.mode==='ai'){state.aux=setInterval(()=>{if(Math.random()<(state.difficulty==='hard'?.8:state.difficulty==='easy'?.35:.55)){ai++;q('br3').textContent=ai}},900)}state.timer=setInterval(()=>{time--;q('br2').textContent=time;if(time<=0)endBreakout()},1000);window.breakBrick=()=>{bricks++;q('br1').textContent=bricks};window.endBreakout=()=>{clearInterval(state.timer);clearInterval(state.aux);if(state.mode==='ai')return finishMini(bricks>ai,bricks>ai?`Ai bătut AI ${bricks} vs ${ai}`:`AI mai bun ${ai} vs ${bricks}`,{score:bricks*12,partial:bricks>ai?1:.35});if(state.mode==='quiz'){if(bricks<target)return finishMini(false,'Sub target',{score:bricks*10,partial:.25});return askQuiz(()=>finishMini(true,'Breakout + quiz',{score:bricks*12}),()=>finishMini(false,'Quiz greșit',{score:bricks*8,partial:.4}))}finishMini(bricks>=target,bricks>=target?'Run reușit':'Sub target',{score:bricks*12,partial:bricks>=target?1:.25})}}

function startMaze(){let prog=0,traps=0,target=state.difficulty==='hard'?8:state.difficulty==='easy'?4:6;layoutGame(`${currentTile().icon} Maze`,`Mergi spre ieșire și evită capcanele.`,[{k:'Progress',v:`0/${target}`,id:'mz1'},{k:'Traps',v:0,id:'mz2'},{k:'Mode',v:state.mode},{k:'Reward',v:currentReward()}],`<div class="btnrow"><button class="btn-main" onclick="mazeStep('left')">◀</button><button class="btn-main" onclick="mazeStep('up')">▲</button><button class="btn-main" onclick="mazeStep('down')">▼</button><button class="btn-main" onclick="mazeStep('right')">▶</button></div>`);window.mazeStep=(d)=>{const ok=Math.random()<(d==='right'?.72:.45);if(ok)prog++;else traps++;q('mz1').textContent=`${prog}/${target}`;q('mz2').textContent=traps;if(prog>=target){const score=120-traps*15;if(state.mode==='quiz')return askQuiz(()=>finishMini(true,'Maze + quiz',{score}),()=>finishMini(false,'Quiz greșit',{score,partial:.4}));if(state.mode==='ai'){const ai=state.difficulty==='hard'?6:state.difficulty==='easy'?2:4;return finishMini(traps<ai,traps<ai?'Ai ieșit mai curat':'AI ar fi avut mai puține traps',{score,partial:traps<ai?1:.35})}return finishMini(true,'Ai ieșit din labirint',{score})}if(traps>=3)return finishMini(false,'Prea multe capcane',{score:35+prog*10,partial:.25})}}

function startShooter(){let score=0,boss=3,target=state.difficulty==='hard'?14:state.difficulty==='easy'?8:11;layoutGame(`${currentTile().icon} Shooter`,`Crește score-ul și termină boss-ul.`,[{k:'Score',v:0,id:'sh1'},{k:'Boss',v:3,id:'sh2'},{k:'Target',v:target},{k:'Reward',v:currentReward()}],`<div class="btnrow"><button class="btn-main" onclick="wave()">⚡ Wave</button><button class="btn-alt" onclick="bossHit()">👾 Boss</button></div>`);function check(){if(score>=target&&boss<=0){if(state.mode==='quiz')return askQuiz(()=>finishMini(true,'Shooter + quiz',{score:score*10}),()=>finishMini(false,'Quiz greșit',{score:score*6,partial:.4}));if(state.mode==='ai'){const ai=state.difficulty==='hard'?16:state.difficulty==='easy'?8:12;return finishMini(score>ai,score>ai?`Ai depășit AI ${score} vs ${ai}`:`AI ar fi avut ${ai}`,{score:score*10,partial:score>ai?1:.35})}return finishMini(true,'Sector curățat',{score:score*10})}}window.wave=()=>{score+=Math.random()<.7?2:1;q('sh1').textContent=score;check()};window.bossHit=()=>{if(score>=Math.max(4,target-4))boss--;q('sh2').textContent=boss;check()}}

function startFusion(){let score=0,orders=0,bombs=3,target=state.difficulty==='hard'?12:state.difficulty==='easy'?7:9;layoutGame(`${currentTile().icon} Fusion`,`Combină mecanici arcade.`,[{k:'Score',v:0,id:'fu1'},{k:'Orders',v:'0/3',id:'fu2'},{k:'Bombs',v:3,id:'fu3'},{k:'Reward',v:currentReward()}],`<div class="btnrow"><button class="btn-main" onclick="fusionAct('orb')">✦ Orb</button><button class="btn-main" onclick="fusionAct('bomb')">💣 Bomb</button><button class="btn-main" onclick="fusionAct('serve')">♨ Serve</button></div>`);window.fusionAct=(a)=>{if(a==='orb')score+=2;if(a==='bomb'&&bombs>0){bombs--;score+=3}if(a==='serve'){orders++;score+=2}q('fu1').textContent=score;q('fu2').textContent=`${orders}/3`;q('fu3').textContent=bombs;if(score>=target&&orders>=3){const s=score*11+bombs*8;if(state.mode==='quiz')return askQuiz(()=>finishMini(true,'Fusion + quiz',{score:s}),()=>finishMini(false,'Quiz greșit',{score:s,partial:.4}));if(state.mode==='ai'){const ai=state.difficulty==='hard'?14:state.difficulty==='easy'?8:11;return finishMini(score>ai,score>ai?'Ai depășit AI în Fusion':'AI ar fi avut score mai bun',{score:s,partial:score>ai?1:.35})}return finishMini(true,'Fusion clear',{score:s})}}}

function startPvAI(){let php=3,ahp=3;layoutGame(`${currentTile().icon} PvAI`,`Attack bate Feint, Block bate Attack, Feint bate Block.`,[{k:'Player HP',v:3,id:'pv1'},{k:'AI HP',v:3,id:'pv2'},{k:'Mode',v:state.mode},{k:'Reward',v:currentReward()}],`<div class="choices">${['attack','block','feint'].map(a=>`<div class="choice"><div class="t">${a}</div><button class="btn-main" onclick="pvPick('${a}')">Alege</button></div>`).join('')}</div>`);const counter=a=>a==='attack'?'block':a==='block'?'feint':'attack';window.pvPick=(a)=>{const all=['attack','block','feint'];const ai=state.mode==='ai'?(state.difficulty==='hard'&&Math.random()<.8?counter(a):all[rand(0,2)]):all[rand(0,2)];if(a===ai){}else if((a==='attack'&&ai==='feint')||(a==='block'&&ai==='attack')||(a==='feint'&&ai==='block'))ahp--;else php--;q('pv1').textContent=php;q('pv2').textContent=ahp;if(php<=0||ahp<=0){const score=Math.max(20,php*35+(3-ahp)*20);if(state.mode==='quiz'){if(ahp>=php)return finishMini(false,'Duel pierdut',{score,partial:.3});return askQuiz(()=>finishMini(true,'Duel + quiz',{score}),()=>finishMini(false,'Quiz greșit',{score,partial:.4}))}if(ahp<php)return finishMini(true,'Duel câștigat',{score});if(ahp===php)return finishMini(false,'Egal',{score,partial:.7});finishMini(false,'AI a câștigat duelul',{score,partial:.25})}}}

function openFullGame(){const t=currentTile();if(!t.url)return toast('Nu există URL','red');const p=currentPlayer();p.full.started++;state.fullSession=bridge.open({player:state.activePlayer,tile:p.position,url:t.url,gameId:t.id,name:t.name});q('modalTitle').textContent=t.icon+' '+t.name;q('modalSub').textContent='Original embedded run · waiting handshake';q('fullFrame').src=t.url;q('fullModal').classList.add('open');save();renderAll()}
function monitorFullSession(){if(!state.fullSession)return;const stale=Date.now()-(state.fullSession.lastEventAt||state.fullSession.startedAt||0);if(stale<FULL_HEARTBEAT_TIMEOUT_MS)return;state.fullSession.status='timeout';q('modalSub').textContent='Run timeout';toast('Full game timeout','red');save()}
function closeFullGame(){q('fullFrame').src='about:blank';q('fullModal').classList.remove('open');bridge.close();state.fullSession=null;save();renderAll()}
function openFullInTab(){if(state.fullSession)window.open(state.fullSession.url,'_blank','noopener,noreferrer')}
function claimFull(result,payload={}){if(!state.fullSession)return;const p=state.players[state.fullSession.player];state.activePlayer=state.fullSession.player;state.selectedTile=p.position;p.full.finished++;p.full.lastResult=result;p.full.lastHeartbeat=Date.now();p.full.connected=!!state.fullSession.lastEventAt;const score=Number(payload.score||state.fullSession.score||0);if(result==='win'){p.full.wins++;state.mode='full';const rr=claimReward(true,{coins:40+(payload.coins||0),xp:30+(payload.xp||0),score:score||180,partial:1.2,result:'full-win',source:'full'});burst();renderScreen('event',`<div class="event-card"><h3>🕹️ Full WIN</h3><p class="muted">Coins +${rr.coins} · XP +${rr.xp}</p><p class="tiny">Bridge: ${state.fullSession.status||'manual'} · Score ${score||180}</p></div>`)}else{state.mode='full';const label=result==='abandon'?'⛔ Abandon':'🏁 Full FINISH';const rr=claimReward(result==='finish'?false:false,{coins:20+(payload.coins||0),xp:14+(payload.xp||0),score:score||110,partial:result==='abandon'?.45:.75,result:'full-finish',source:'full'});renderScreen('event',`<div class="event-card"><h3>${label}</h3><p class="muted">Coins +${rr.coins} · XP +${rr.xp}</p><p class="tiny">Bridge: ${state.fullSession.status||'manual'} · Score ${score||110}</p></div>`)}closeFullGame();save();renderAll()}
window.addEventListener('message',ev=>{const packet=bridge.receive(ev);if(!packet||packet.kind!=='accepted'||!state.fullSession)return;const data=packet.data;if(data.type==='arcade-world-handshake'){q('modalSub').textContent='Bridge connected';save();return}if(data.type==='arcade-world-start'){q('modalSub').textContent='Run started';save();return}if(data.type==='arcade-world-progress'){q('modalSub').textContent=`Run live · score ${Number(data.score||0)}`;save();return}if(data.type==='arcade-world-reconnect'){q('modalSub').textContent='Run reconnected';save();return}if(data.type==='arcade-world-timeout'){q('modalSub').textContent='Run timeout';toast('Full game timeout','red');save();return}if(data.type==='arcade-world-result'){if(data.result==='win')return claimFull('win',data);if(data.result==='finish'||data.result==='lose')return claimFull('finish',data);if(data.result==='abandon')return claimFull('abandon',data)}})

function toggleModal(id,on){q(id).classList[on?'add':'remove']('open')}
function openSavePanel(){toggleModal('saveModal',true)}
function exportSave(){q('saveText').value=exportState(state);toast('Save exportat','green')}
function importSave(){try{importState(state,q('saveText').value);ensurePlayers();save();renderAll();renderScreen('details');toast('Save importat','green')}catch(e){toast('Import invalid','red')}}
function saveProfileSlot(n){localStorage.setItem(PROFILE_PREFIX+n,localStorage.getItem(STORAGE)||JSON.stringify(defaultSave()));toast(`Slot ${n} salvat`,'green')}
function loadProfileSlot(n){const s=localStorage.getItem(PROFILE_PREFIX+n);if(!s)return toast('Slot gol','red');localStorage.setItem(STORAGE,s);load();ensurePlayers();renderAll();renderScreen('details');toast(`Slot ${n} încărcat`,'green')}
function partialReset(type){if(type==='stats'){for(const p of state.players){p.stats={};p.history=[];p.totalWins=0;p.full={started:0,finished:0,wins:0};p.completed=[];p.questsDone=[]}}if(type==='inventory'){for(const p of state.players){p.inventory={shield:0,reroll:0,double:0,themeToken:0};p.chests={common:0,rare:0,epic:0};p.shopBuys=0}}if(type==='board'){for(const p of state.players){p.position=0;p.visited=[0];p.completed=[];p.boardPasses=0;p.bonusHits=0;p.trapHits=0;p.skipTurns=0;p.bonusTurns=0}}save();renderAll();toast(`Reset ${type}`,'red')}
function hardReset(){localStorage.removeItem(STORAGE);state.players=[defaultPlayer(0),defaultPlayer(1)];state.activePlayer=0;state.selectedTile=0;state.multiplayerCount=2;state.themeIndex=0;state.sound=true;save();renderAll();renderScreen('details');toast('Reset complet','red')}

window.selectTile=selectTile;window.setPlayerCount=setPlayerCount;window.buyItem=buyItem;window.toggleSound=toggleSound;window.nextTheme=nextTheme;window.rollDice=rollDice;window.useBonusTurn=useBonusTurn;window.chooseMode=chooseMode;window.chooseDifficulty=chooseDifficulty;window.endTurn=endTurn;window.renderScreen=renderScreen;window.startCurrentMini=launchMini;window.openFullGame=openFullGame;window.openFullInTab=openFullInTab;window.claimFull=claimFull;window.closeFullGame=closeFullGame;window.toggleModal=toggleModal;window.openSavePanel=openSavePanel;window.exportSave=exportSave;window.importSave=importSave;window.saveProfileSlot=saveProfileSlot;window.loadProfileSlot=loadProfileSlot;window.partialReset=partialReset;window.hardReset=hardReset;

function init(){load();ensurePlayers();state.daily=buildDaily();document.body.className=THEMES[state.themeIndex];renderAll();renderScreen('details');setHint('Alege 2–4 jucători sau aruncă zarul.')}
window.addEventListener('resize',()=>requestAnimationFrame(()=>{drawConnectors();moveTokenTo(currentPlayer().position,false)}))
window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(q('fullModal').classList.contains('open'))closeFullGame();if(q('saveModal').classList.contains('open'))toggleModal('saveModal',false)}})
setInterval(monitorFullSession,5000)
init();
